config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'exchange#index'
  get '/convert', to: 'exchange#convert'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exchange_controller.rb
# frozen_string_literal: true

require_relative '../client/exchange_rate'

#  A controller class for currency exchange
class ExchangeController < ApplicationController
  before_action :exchange_rate_api_client

  def index
    @currency_types = @client.extract_currency_types
  end

  def convert
    usd_amount = params[:amount].to_f
    selected_currency_type = params[:currency]

    rate = @client.extract_rate_for(currency_type: selected_currency_type)
    @calculated_amount = calculate(usd_amount, rate)
  end

  private

  def exchange_rate_api_client
    @client = validate_client(Client::ExchangeRate.new)
  end

  def validate_client(client)
    return client unless client.response_hash['alert']

    @currency_types = []
    flash[:alert] = client.response_hash['alert']
    render action: :index
  end

  def calculate(usd_amount, rate)
    (usd_amount * rate).round(2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exchange/convert.html.erb
<div style="text-align: center">Calculated amount: <%=@calculated_amount%></div>

app/views/exchange/index.html.erb
<div style="text-align: center">
  <% if flash[:alert] %>
    <div style="color: red"><%= flash[:alert] %></div>
  <% end %>
  <%= form_with(url: convert_path, method: 'get', local: true) do %>
    <%= label_tag :amount, 'USD amount '%>
    <%= number_field_tag :amount, '0', value: number_to_currency(params[:amount].to_f, delimiter: '', unit: ''), step: 0.01%>
    <%= label_tag :currency, ' To '%>
    <%= select_tag(:currency, options_for_select(@currency_types, 'CAD')) %>
    <%= button_tag 'Convert' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExchangeRateTool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>